version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8088:8080
      - 50000:50000
    container_name: jenkins
    restart: always
    volumes:
      - E:\projects\jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock