apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo5-deployment
  namespace: k8s-youssefs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
        - name: yolo
          image: youssefcarmi92/k8s_yolo5_jenkins:latest
          ports:
            - containerPort: 8081
          command: ["python3"]
          args: ["app.py"]
          resources:
            requests:
              cpu: "500m"
              memory: "128Mi"
            limits:
              cpu: "1"
              memory: "256Mi"
