---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "gp2"
  persistentVolumeReclaimPolicy: Retain
  awsElasticBlockStore:
    volumeID: vol-0331a096e5d95fd33
    fsType: ext4
