---
- hosts: all
  gather_facts: false
  tasks:
    
    - name: Ping hosts
      ping:
      register: result


    - name: Create directory
      file:
        path: /home/ubuntu/ansible_test
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'
      when: result is success

    - name: Create file
      file:
        path: /home/ubuntu/ansible_test/test.txt
        state: touch
        owner: ubuntu
        group: ubuntu
        mode: '0644'
      when: 
      - result is success 




