version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - D:\atech_devops\mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    restart: always
    networks:
      - my_network
    
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports: 
      - "8080:8080"
      - "50000:50000"
    volumes:
      - D:\atech_devops\jenkins:/var/jenkins_home
    restart: always
    depends_on:
      - mongodb

    networks:
      - my_network  



networks:
  my_network:
    driver: bridge    



# use docker-compose up -d